name = "work-works"
main = "src/index.ts"
compatibility_date = "2022-08-16"

[build]
command = "yarn build-storybook"

[site]
bucket = "./storybook-static"

[env.preview]
# route = "bouquet-preview.peony.ink/*"

[env.production]
# route = "bouquet.peony.ink/*"
