name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TMP_GITHUB_TOKEN }}

      - name: Install dependencies
        run: yarn

      # - name: Run tests
      #   run: yarn lint && yarn test

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: yarn deploy:wr -e production
